import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import { signOut, useSession } from '../../node_modules/next-auth/client'
import styles from '../styles/Home.module.css'
 type userProps={
        name:string;
        email:string;
        image:string;
    }


export default function Authentication() {

const [user,setUser]=useState<userProps>()

  const[session]=useSession()    

  useEffect(()=>{
    setUser(session?.user)
  },[])
    return (
 <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Olá <a href="https://nextjs.org"> {user?.name} </a>
        </h1>
          <img src={user?.image} alt="" />
        <p className={styles.description}>
            
           
        </p>
        <p>
          <button onClick={()=> signOut() } >Sair</button>
        </p>

       
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
          
          </span>
        </a>
      </footer>
    </div>
    )
}
