import Head from 'next/head';
import React from 'react';
import { signIn, signOut } from '../../node_modules/next-auth/client';
import styles from '../styles/Home.module.css'
import SubscribeButton from './SubscribeButton';
import Image from 'next/image'




export function LoginScreen (){

  return(
     <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Confirme sua Presença no nosso Casamento <a href="https://nextjs.org">  </a>
        </h1>
         
        <p className={styles.description}>
           <button type="button" onClick={()=>signIn('github')} >Confirmar com GitHub</button>
          
        </p>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
    )}